// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: github.com/dogmatiq/interopspec/configspec/configapi.proto

package configspec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageRole is an enumeration of the roles that a message can play within an
// application.
type MessageRole int32

const (
	MessageRole_UNKNOWN_MESSAGE_ROLE MessageRole = 0
	MessageRole_COMMAND              MessageRole = 1
	MessageRole_EVENT                MessageRole = 2
	MessageRole_TIMEOUT              MessageRole = 3
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "UNKNOWN_MESSAGE_ROLE",
		1: "COMMAND",
		2: "EVENT",
		3: "TIMEOUT",
	}
	MessageRole_value = map[string]int32{
		"UNKNOWN_MESSAGE_ROLE": 0,
		"COMMAND":              1,
		"EVENT":                2,
		"TIMEOUT":              3,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_enumTypes[0].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_enumTypes[0]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescGZIP(), []int{0}
}

// HandlerType is an enumeration of the types of handlers that an application
// can contain.
type HandlerType int32

const (
	HandlerType_UNKNOWN_HANDLER_TYPE HandlerType = 0
	HandlerType_AGGREGATE            HandlerType = 1
	HandlerType_PROCESS              HandlerType = 2
	HandlerType_INTEGRATION          HandlerType = 3
	HandlerType_PROJECTION           HandlerType = 4
)

// Enum value maps for HandlerType.
var (
	HandlerType_name = map[int32]string{
		0: "UNKNOWN_HANDLER_TYPE",
		1: "AGGREGATE",
		2: "PROCESS",
		3: "INTEGRATION",
		4: "PROJECTION",
	}
	HandlerType_value = map[string]int32{
		"UNKNOWN_HANDLER_TYPE": 0,
		"AGGREGATE":            1,
		"PROCESS":              2,
		"INTEGRATION":          3,
		"PROJECTION":           4,
	}
)

func (x HandlerType) Enum() *HandlerType {
	p := new(HandlerType)
	*p = x
	return p
}

func (x HandlerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandlerType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_enumTypes[1].Descriptor()
}

func (HandlerType) Type() protoreflect.EnumType {
	return &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_enumTypes[1]
}

func (x HandlerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandlerType.Descriptor instead.
func (HandlerType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescGZIP(), []int{1}
}

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescGZIP(), []int{0}
}

type ListApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescGZIP(), []int{1}
}

func (x *ListApplicationsResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

// Application represents a Dogma application hosted by the engine on the
// server.
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity is the application's identity.
	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// GoType is the fully-qualified name of the Go type that provides as the
	// application's implementation.
	GoType string `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	// Handlers is the set of handlers within the application.
	Handlers      []*Handler `protobuf:"bytes,3,rep,name=handlers,proto3" json:"handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescGZIP(), []int{2}
}

func (x *Application) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Application) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *Application) GetHandlers() []*Handler {
	if x != nil {
		return x.Handlers
	}
	return nil
}

// Handler is a message handler within an application.
type Handler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity is the handler's identity.
	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// GoType is the fully-qualified name of the Go type that provides as the
	// handler's implementation.
	GoType string `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	// Type is the handler's type.
	Type HandlerType `protobuf:"varint,3,opt,name=type,proto3,enum=dogma.interop.v1.config.HandlerType" json:"type,omitempty"`
	// ProducedMessages is the set of messages produced by this handler.
	//
	// The keys are the fully-qualified names of the message's Go type and the
	// value is the role that message plays within the application.
	ProducedMessages map[string]MessageRole `protobuf:"bytes,4,rep,name=produced_messages,json=producedMessages,proto3" json:"produced_messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=dogma.interop.v1.config.MessageRole"`
	// ConsumedMessages is the set of messages consumed by this handler.
	//
	// The keys are the fully-qualified names of the message's Go type and the
	// value is the role that message plays within the application.
	ConsumedMessages map[string]MessageRole `protobuf:"bytes,5,rep,name=consumed_messages,json=consumedMessages,proto3" json:"consumed_messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=dogma.interop.v1.config.MessageRole"`
	// IsDisabled indicates whether the handler is disabled.
	IsDisabled    bool `protobuf:"varint,6,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handler) Reset() {
	*x = Handler{}
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handler) ProtoMessage() {}

func (x *Handler) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handler.ProtoReflect.Descriptor instead.
func (*Handler) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescGZIP(), []int{3}
}

func (x *Handler) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Handler) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *Handler) GetType() HandlerType {
	if x != nil {
		return x.Type
	}
	return HandlerType_UNKNOWN_HANDLER_TYPE
}

func (x *Handler) GetProducedMessages() map[string]MessageRole {
	if x != nil {
		return x.ProducedMessages
	}
	return nil
}

func (x *Handler) GetConsumedMessages() map[string]MessageRole {
	if x != nil {
		return x.ConsumedMessages
	}
	return nil
}

func (x *Handler) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

// Identity represents the identity of an application or handler.
type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the entity's unique name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key is the entity's immutable, unique key.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescGZIP(), []int{4}
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_github_com_dogmatiq_interopspec_configspec_configapi_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDesc = "" +
	"\n" +
	":github.com/dogmatiq/interopspec/configspec/configapi.proto\x12\x17dogma.interop.v1.config\"\x19\n" +
	"\x17ListApplicationsRequest\"d\n" +
	"\x18ListApplicationsResponse\x12H\n" +
	"\fapplications\x18\x01 \x03(\v2$.dogma.interop.v1.config.ApplicationR\fapplications\"\xa3\x01\n" +
	"\vApplication\x12=\n" +
	"\bidentity\x18\x01 \x01(\v2!.dogma.interop.v1.config.IdentityR\bidentity\x12\x17\n" +
	"\ago_type\x18\x02 \x01(\tR\x06goType\x12<\n" +
	"\bhandlers\x18\x03 \x03(\v2 .dogma.interop.v1.config.HandlerR\bhandlers\"\xdc\x04\n" +
	"\aHandler\x12=\n" +
	"\bidentity\x18\x01 \x01(\v2!.dogma.interop.v1.config.IdentityR\bidentity\x12\x17\n" +
	"\ago_type\x18\x02 \x01(\tR\x06goType\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2$.dogma.interop.v1.config.HandlerTypeR\x04type\x12c\n" +
	"\x11produced_messages\x18\x04 \x03(\v26.dogma.interop.v1.config.Handler.ProducedMessagesEntryR\x10producedMessages\x12c\n" +
	"\x11consumed_messages\x18\x05 \x03(\v26.dogma.interop.v1.config.Handler.ConsumedMessagesEntryR\x10consumedMessages\x12\x1f\n" +
	"\vis_disabled\x18\x06 \x01(\bR\n" +
	"isDisabled\x1ai\n" +
	"\x15ProducedMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\x0e2$.dogma.interop.v1.config.MessageRoleR\x05value:\x028\x01\x1ai\n" +
	"\x15ConsumedMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\x0e2$.dogma.interop.v1.config.MessageRoleR\x05value:\x028\x01\"0\n" +
	"\bIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key*L\n" +
	"\vMessageRole\x12\x18\n" +
	"\x14UNKNOWN_MESSAGE_ROLE\x10\x00\x12\v\n" +
	"\aCOMMAND\x10\x01\x12\t\n" +
	"\x05EVENT\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03*d\n" +
	"\vHandlerType\x12\x18\n" +
	"\x14UNKNOWN_HANDLER_TYPE\x10\x00\x12\r\n" +
	"\tAGGREGATE\x10\x01\x12\v\n" +
	"\aPROCESS\x10\x02\x12\x0f\n" +
	"\vINTEGRATION\x10\x03\x12\x0e\n" +
	"\n" +
	"PROJECTION\x10\x042\x84\x01\n" +
	"\tConfigAPI\x12w\n" +
	"\x10ListApplications\x120.dogma.interop.v1.config.ListApplicationsRequest\x1a1.dogma.interop.v1.config.ListApplicationsResponseB,Z*github.com/dogmatiq/interopspec/configspecb\x06proto3"

var (
	file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescData []byte
)

func file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDescData
}

var file_github_com_dogmatiq_interopspec_configspec_configapi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_github_com_dogmatiq_interopspec_configspec_configapi_proto_goTypes = []any{
	(MessageRole)(0),                 // 0: dogma.interop.v1.config.MessageRole
	(HandlerType)(0),                 // 1: dogma.interop.v1.config.HandlerType
	(*ListApplicationsRequest)(nil),  // 2: dogma.interop.v1.config.ListApplicationsRequest
	(*ListApplicationsResponse)(nil), // 3: dogma.interop.v1.config.ListApplicationsResponse
	(*Application)(nil),              // 4: dogma.interop.v1.config.Application
	(*Handler)(nil),                  // 5: dogma.interop.v1.config.Handler
	(*Identity)(nil),                 // 6: dogma.interop.v1.config.Identity
	nil,                              // 7: dogma.interop.v1.config.Handler.ProducedMessagesEntry
	nil,                              // 8: dogma.interop.v1.config.Handler.ConsumedMessagesEntry
}
var file_github_com_dogmatiq_interopspec_configspec_configapi_proto_depIdxs = []int32{
	4,  // 0: dogma.interop.v1.config.ListApplicationsResponse.applications:type_name -> dogma.interop.v1.config.Application
	6,  // 1: dogma.interop.v1.config.Application.identity:type_name -> dogma.interop.v1.config.Identity
	5,  // 2: dogma.interop.v1.config.Application.handlers:type_name -> dogma.interop.v1.config.Handler
	6,  // 3: dogma.interop.v1.config.Handler.identity:type_name -> dogma.interop.v1.config.Identity
	1,  // 4: dogma.interop.v1.config.Handler.type:type_name -> dogma.interop.v1.config.HandlerType
	7,  // 5: dogma.interop.v1.config.Handler.produced_messages:type_name -> dogma.interop.v1.config.Handler.ProducedMessagesEntry
	8,  // 6: dogma.interop.v1.config.Handler.consumed_messages:type_name -> dogma.interop.v1.config.Handler.ConsumedMessagesEntry
	0,  // 7: dogma.interop.v1.config.Handler.ProducedMessagesEntry.value:type_name -> dogma.interop.v1.config.MessageRole
	0,  // 8: dogma.interop.v1.config.Handler.ConsumedMessagesEntry.value:type_name -> dogma.interop.v1.config.MessageRole
	2,  // 9: dogma.interop.v1.config.ConfigAPI.ListApplications:input_type -> dogma.interop.v1.config.ListApplicationsRequest
	3,  // 10: dogma.interop.v1.config.ConfigAPI.ListApplications:output_type -> dogma.interop.v1.config.ListApplicationsResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_interopspec_configspec_configapi_proto_init() }
func file_github_com_dogmatiq_interopspec_configspec_configapi_proto_init() {
	if File_github_com_dogmatiq_interopspec_configspec_configapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_configspec_configapi_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_dogmatiq_interopspec_configspec_configapi_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_interopspec_configspec_configapi_proto_depIdxs,
		EnumInfos:         file_github_com_dogmatiq_interopspec_configspec_configapi_proto_enumTypes,
		MessageInfos:      file_github_com_dogmatiq_interopspec_configspec_configapi_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_interopspec_configspec_configapi_proto = out.File
	file_github_com_dogmatiq_interopspec_configspec_configapi_proto_goTypes = nil
	file_github_com_dogmatiq_interopspec_configspec_configapi_proto_depIdxs = nil
}
