// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: github.com/dogmatiq/interopspec/envelopespec/envelope.proto

package envelopespec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is a container for a marshaled message and it meta-data.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageId is a unique identifier for the message.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// CausationId is the ID of the message that was the direct cause of the
	// message in this envelope.
	//
	// It is equal to MessageId if this message was not caused by any other.
	CausationId string `protobuf:"bytes,2,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	// CorrelationId is the ID of the first ancestor of the message in this
	// envelope that was not caused by another message.
	//
	// It is equal to MessageId if this message was not caused by any other.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// SourceSite is the (optional) identity of the site that the source
	// application is running within.
	//
	// The site is used to disambiguate between messages from different
	// installations of the same application.
	SourceSite *Identity `protobuf:"bytes,13,opt,name=source_site,json=sourceSite,proto3" json:"source_site,omitempty"`
	// SourceApplication is the identity of the Dogma application that produced
	// the message in this envelope.
	SourceApplication *Identity `protobuf:"bytes,4,opt,name=source_application,json=sourceApplication,proto3" json:"source_application,omitempty"`
	// SourceHandler is the identity of the Dogma handler that produced the
	// message in this envelope.
	//
	// It is the zero-value if the message was not produced by a handler.
	SourceHandler *Identity `protobuf:"bytes,5,opt,name=source_handler,json=sourceHandler,proto3" json:"source_handler,omitempty"`
	// SourceInstanceId is the ID of the aggregate or process instance that
	// produced the message in this envelope.
	//
	// It is empty if the message was not produced by an aggregate or process
	// handler.
	SourceInstanceId string `protobuf:"bytes,6,opt,name=source_instance_id,json=sourceInstanceId,proto3" json:"source_instance_id,omitempty"`
	// CreatedAt is the time at which the message was created, marshaled in
	// RFC-3339 format, with nanoseconds.
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ScheduledFor is the time at which a timeout message is scheduled to be
	// handled, marshaled in RFC-3339 format, with nanoseconds.
	//
	// It is empty for command and event messages.
	ScheduledFor string `protobuf:"bytes,8,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	// Description is an optional human-readable description of the message.
	Description string `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	// PortableName is the unique name used to identify messages of this type.
	PortableName string `protobuf:"bytes,10,opt,name=portable_name,json=portableName,proto3" json:"portable_name,omitempty"`
	// MediaType is a MIME media-type describing the content and encoding of the
	// binary message data.
	MediaType string `protobuf:"bytes,11,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// Data is the binary message data.
	//
	// The data format is described by MediaType, the allowed values of both are
	// outside the scope of this specification.
	Data          []byte `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetSourceSite() *Identity {
	if x != nil {
		return x.SourceSite
	}
	return nil
}

func (x *Envelope) GetSourceApplication() *Identity {
	if x != nil {
		return x.SourceApplication
	}
	return nil
}

func (x *Envelope) GetSourceHandler() *Identity {
	if x != nil {
		return x.SourceHandler
	}
	return nil
}

func (x *Envelope) GetSourceInstanceId() string {
	if x != nil {
		return x.SourceInstanceId
	}
	return ""
}

func (x *Envelope) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Envelope) GetScheduledFor() string {
	if x != nil {
		return x.ScheduledFor
	}
	return ""
}

func (x *Envelope) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Envelope) GetPortableName() string {
	if x != nil {
		return x.PortableName
	}
	return ""
}

func (x *Envelope) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Envelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Identity represents the identity of an application or handler.
type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the entity's unique name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key is the entity's immutable, unique key.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_github_com_dogmatiq_interopspec_envelopespec_envelope_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDesc = "" +
	"\n" +
	";github.com/dogmatiq/interopspec/envelopespec/envelope.proto\x12\x19dogma.interop.v1.envelope\"\xc5\x04\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\fcausation_id\x18\x02 \x01(\tR\vcausationId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12D\n" +
	"\vsource_site\x18\r \x01(\v2#.dogma.interop.v1.envelope.IdentityR\n" +
	"sourceSite\x12R\n" +
	"\x12source_application\x18\x04 \x01(\v2#.dogma.interop.v1.envelope.IdentityR\x11sourceApplication\x12J\n" +
	"\x0esource_handler\x18\x05 \x01(\v2#.dogma.interop.v1.envelope.IdentityR\rsourceHandler\x12,\n" +
	"\x12source_instance_id\x18\x06 \x01(\tR\x10sourceInstanceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12#\n" +
	"\rscheduled_for\x18\b \x01(\tR\fscheduledFor\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12#\n" +
	"\rportable_name\x18\n" +
	" \x01(\tR\fportableName\x12\x1d\n" +
	"\n" +
	"media_type\x18\v \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\f \x01(\fR\x04data\"0\n" +
	"\bIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03keyB.Z,github.com/dogmatiq/interopspec/envelopespecb\x06proto3"

var (
	file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDescData []byte
)

func file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDescData
}

var file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: dogma.interop.v1.envelope.Envelope
	(*Identity)(nil), // 1: dogma.interop.v1.envelope.Identity
}
var file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_depIdxs = []int32{
	1, // 0: dogma.interop.v1.envelope.Envelope.source_site:type_name -> dogma.interop.v1.envelope.Identity
	1, // 1: dogma.interop.v1.envelope.Envelope.source_application:type_name -> dogma.interop.v1.envelope.Identity
	1, // 2: dogma.interop.v1.envelope.Envelope.source_handler:type_name -> dogma.interop.v1.envelope.Identity
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_init() }
func file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_init() {
	if File_github_com_dogmatiq_interopspec_envelopespec_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_interopspec_envelopespec_envelope_proto = out.File
	file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_goTypes = nil
	file_github_com_dogmatiq_interopspec_envelopespec_envelope_proto_depIdxs = nil
}
