// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: github.com/dogmatiq/interopspec/discoverspec/discoverapi.proto

package discoverspec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchApplicationsRequest) Reset() {
	*x = WatchApplicationsRequest{}
	mi := &file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchApplicationsRequest) ProtoMessage() {}

func (x *WatchApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchApplicationsRequest.ProtoReflect.Descriptor instead.
func (*WatchApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescGZIP(), []int{0}
}

type WatchApplicationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity is the identity key of the Dogma application that the response is
	// about.
	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// SourceSite is the (optional) identity of the site that the application is
	// running within.
	//
	// The site is used to disambiguate between messages from different
	// installations of the same application.
	Site *Identity `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty"`
	// Available indicates whether the application should currently be considered
	// available or not.
	Available     bool `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchApplicationsResponse) Reset() {
	*x = WatchApplicationsResponse{}
	mi := &file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchApplicationsResponse) ProtoMessage() {}

func (x *WatchApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchApplicationsResponse.ProtoReflect.Descriptor instead.
func (*WatchApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescGZIP(), []int{1}
}

func (x *WatchApplicationsResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *WatchApplicationsResponse) GetSite() *Identity {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *WatchApplicationsResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

// Identity represents the identity of an application.
type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the application's unique name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key is the application's immutable, unique key.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescGZIP(), []int{2}
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDesc = "" +
	"\n" +
	">github.com/dogmatiq/interopspec/discoverspec/discoverapi.proto\x12\x19dogma.interop.v1.discover\"\x1a\n" +
	"\x18WatchApplicationsRequest\"\xb3\x01\n" +
	"\x19WatchApplicationsResponse\x12?\n" +
	"\bidentity\x18\x01 \x01(\v2#.dogma.interop.v1.discover.IdentityR\bidentity\x127\n" +
	"\x04site\x18\x03 \x01(\v2#.dogma.interop.v1.discover.IdentityR\x04site\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\"0\n" +
	"\bIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key2\x90\x01\n" +
	"\vDiscoverAPI\x12\x80\x01\n" +
	"\x11WatchApplications\x123.dogma.interop.v1.discover.WatchApplicationsRequest\x1a4.dogma.interop.v1.discover.WatchApplicationsResponse0\x01B.Z,github.com/dogmatiq/interopspec/discoverspecb\x06proto3"

var (
	file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescData []byte
)

func file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDescData
}

var file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_goTypes = []any{
	(*WatchApplicationsRequest)(nil),  // 0: dogma.interop.v1.discover.WatchApplicationsRequest
	(*WatchApplicationsResponse)(nil), // 1: dogma.interop.v1.discover.WatchApplicationsResponse
	(*Identity)(nil),                  // 2: dogma.interop.v1.discover.Identity
}
var file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_depIdxs = []int32{
	2, // 0: dogma.interop.v1.discover.WatchApplicationsResponse.identity:type_name -> dogma.interop.v1.discover.Identity
	2, // 1: dogma.interop.v1.discover.WatchApplicationsResponse.site:type_name -> dogma.interop.v1.discover.Identity
	0, // 2: dogma.interop.v1.discover.DiscoverAPI.WatchApplications:input_type -> dogma.interop.v1.discover.WatchApplicationsRequest
	1, // 3: dogma.interop.v1.discover.DiscoverAPI.WatchApplications:output_type -> dogma.interop.v1.discover.WatchApplicationsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_init() }
func file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_init() {
	if File_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto = out.File
	file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_goTypes = nil
	file_github_com_dogmatiq_interopspec_discoverspec_discoverapi_proto_depIdxs = nil
}
