// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: github.com/dogmatiq/interopspec/eventstreamspec/streamapi.proto

package eventstreamspec

import (
	envelopespec "github.com/dogmatiq/interopspec/envelopespec"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ApplicationKey is the identity key of the application to consume from.
	ApplicationKey string `protobuf:"bytes,1,opt,name=application_key,json=applicationKey,proto3" json:"application_key,omitempty"`
	// EventTypes is a list of event types to be consumed.
	EventTypes []*EventType `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// StartPoint specifies the point within the stream to start consuming.
	//
	// Types that are valid to be assigned to StartPoint:
	//
	//	*ConsumeRequest_Offset
	StartPoint    isConsumeRequest_StartPoint `protobuf_oneof:"start_point"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumeRequest) GetApplicationKey() string {
	if x != nil {
		return x.ApplicationKey
	}
	return ""
}

func (x *ConsumeRequest) GetEventTypes() []*EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *ConsumeRequest) GetStartPoint() isConsumeRequest_StartPoint {
	if x != nil {
		return x.StartPoint
	}
	return nil
}

func (x *ConsumeRequest) GetOffset() uint64 {
	if x != nil {
		if x, ok := x.StartPoint.(*ConsumeRequest_Offset); ok {
			return x.Offset
		}
	}
	return 0
}

type isConsumeRequest_StartPoint interface {
	isConsumeRequest_StartPoint()
}

type ConsumeRequest_Offset struct {
	// Offset is the offset of the earliest message to be consumed.
	//
	// The offset of the message returned will be greater than this value if the
	// event at that offset is not one of the requested event types.
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3,oneof"`
}

func (*ConsumeRequest_Offset) isConsumeRequest_StartPoint() {}

type ConsumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the offset of the message.
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Envelope is the envelope containing the event.
	Envelope      *envelopespec.Envelope `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeResponse) GetEnvelope() *envelopespec.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type EventTypesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ApplicationKey is the identity key of the application to query.
	ApplicationKey string `protobuf:"bytes,1,opt,name=application_key,json=applicationKey,proto3" json:"application_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventTypesRequest) Reset() {
	*x = EventTypesRequest{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypesRequest) ProtoMessage() {}

func (x *EventTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypesRequest.ProtoReflect.Descriptor instead.
func (*EventTypesRequest) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{2}
}

func (x *EventTypesRequest) GetApplicationKey() string {
	if x != nil {
		return x.ApplicationKey
	}
	return ""
}

type EventTypesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EventTypes is a list of event types supported by the server.
	EventTypes    []*EventType `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypesResponse) Reset() {
	*x = EventTypesResponse{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypesResponse) ProtoMessage() {}

func (x *EventTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypesResponse.ProtoReflect.Descriptor instead.
func (*EventTypesResponse) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{3}
}

func (x *EventTypesResponse) GetEventTypes() []*EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type EventType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PortableName is a name that uniquely identifies the event type across
	// process boundaries.
	PortableName string `protobuf:"bytes,1,opt,name=portable_name,json=portableName,proto3" json:"portable_name,omitempty"`
	// MediaTypes is the set of supported media-types that can be used to
	// represents events of this type, in order of preference.
	MediaTypes    []string `protobuf:"bytes,2,rep,name=media_types,json=mediaTypes,proto3" json:"media_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventType) Reset() {
	*x = EventType{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventType) ProtoMessage() {}

func (x *EventType) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventType.ProtoReflect.Descriptor instead.
func (*EventType) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{4}
}

func (x *EventType) GetPortableName() string {
	if x != nil {
		return x.PortableName
	}
	return ""
}

func (x *EventType) GetMediaTypes() []string {
	if x != nil {
		return x.MediaTypes
	}
	return nil
}

// UnrecognizedApplication is an error-details value for INVALID_ARGUMENT
// errors that occurred because a specific application key was not recognized by
// the server.
type UnrecognizedApplication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ApplicationKey is the identity of the application that produced the error.
	ApplicationKey string `protobuf:"bytes,1,opt,name=application_key,json=applicationKey,proto3" json:"application_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnrecognizedApplication) Reset() {
	*x = UnrecognizedApplication{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnrecognizedApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnrecognizedApplication) ProtoMessage() {}

func (x *UnrecognizedApplication) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnrecognizedApplication.ProtoReflect.Descriptor instead.
func (*UnrecognizedApplication) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{5}
}

func (x *UnrecognizedApplication) GetApplicationKey() string {
	if x != nil {
		return x.ApplicationKey
	}
	return ""
}

// UnrecognizedEventType is an error-details value for INVALID_ARGUMENT errors
// that occurred because a specific event type was not recognized by the
// server.
type UnrecognizedEventType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PortableName is a name that uniquely identifies the event type across
	// process boundaries.
	PortableName  string `protobuf:"bytes,2,opt,name=portable_name,json=portableName,proto3" json:"portable_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnrecognizedEventType) Reset() {
	*x = UnrecognizedEventType{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnrecognizedEventType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnrecognizedEventType) ProtoMessage() {}

func (x *UnrecognizedEventType) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnrecognizedEventType.ProtoReflect.Descriptor instead.
func (*UnrecognizedEventType) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{6}
}

func (x *UnrecognizedEventType) GetPortableName() string {
	if x != nil {
		return x.PortableName
	}
	return ""
}

// NoRecognizedMediaTypes is an error-details value for INVALID_ARGUMENT errors
// that occurred because a client requested that events of a specific type be
// encoded using media-types that are not recognized by the server.
type NoRecognizedMediaTypes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PortableName is a name that uniquely identifies the event type across
	// process boundaries.
	PortableName  string `protobuf:"bytes,2,opt,name=portable_name,json=portableName,proto3" json:"portable_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoRecognizedMediaTypes) Reset() {
	*x = NoRecognizedMediaTypes{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoRecognizedMediaTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoRecognizedMediaTypes) ProtoMessage() {}

func (x *NoRecognizedMediaTypes) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoRecognizedMediaTypes.ProtoReflect.Descriptor instead.
func (*NoRecognizedMediaTypes) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{7}
}

func (x *NoRecognizedMediaTypes) GetPortableName() string {
	if x != nil {
		return x.PortableName
	}
	return ""
}

// UnsupportedStartPoint is an error-details value for UNIMPLEMENTED errors that
// occurred because a client started consuming using a start point specified in
// a way that is not supported by the server.
type UnsupportedStartPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsupportedStartPoint) Reset() {
	*x = UnsupportedStartPoint{}
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsupportedStartPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsupportedStartPoint) ProtoMessage() {}

func (x *UnsupportedStartPoint) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsupportedStartPoint.ProtoReflect.Descriptor instead.
func (*UnsupportedStartPoint) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP(), []int{8}
}

var File_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDesc = "" +
	"\n" +
	"?github.com/dogmatiq/interopspec/eventstreamspec/streamapi.proto\x12\x1cdogma.interop.v1.eventstream\x1a;github.com/dogmatiq/interopspec/envelopespec/envelope.proto\"\xac\x01\n" +
	"\x0eConsumeRequest\x12'\n" +
	"\x0fapplication_key\x18\x01 \x01(\tR\x0eapplicationKey\x12H\n" +
	"\vevent_types\x18\x02 \x03(\v2'.dogma.interop.v1.eventstream.EventTypeR\n" +
	"eventTypes\x12\x18\n" +
	"\x06offset\x18\x03 \x01(\x04H\x00R\x06offsetB\r\n" +
	"\vstart_point\"j\n" +
	"\x0fConsumeResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12?\n" +
	"\benvelope\x18\x02 \x01(\v2#.dogma.interop.v1.envelope.EnvelopeR\benvelope\"<\n" +
	"\x11EventTypesRequest\x12'\n" +
	"\x0fapplication_key\x18\x01 \x01(\tR\x0eapplicationKey\"^\n" +
	"\x12EventTypesResponse\x12H\n" +
	"\vevent_types\x18\x01 \x03(\v2'.dogma.interop.v1.eventstream.EventTypeR\n" +
	"eventTypes\"Q\n" +
	"\tEventType\x12#\n" +
	"\rportable_name\x18\x01 \x01(\tR\fportableName\x12\x1f\n" +
	"\vmedia_types\x18\x02 \x03(\tR\n" +
	"mediaTypes\"B\n" +
	"\x17UnrecognizedApplication\x12'\n" +
	"\x0fapplication_key\x18\x01 \x01(\tR\x0eapplicationKey\"<\n" +
	"\x15UnrecognizedEventType\x12#\n" +
	"\rportable_name\x18\x02 \x01(\tR\fportableName\"=\n" +
	"\x16NoRecognizedMediaTypes\x12#\n" +
	"\rportable_name\x18\x02 \x01(\tR\fportableName\"\x17\n" +
	"\x15UnsupportedStartPoint2\xe6\x01\n" +
	"\tStreamAPI\x12h\n" +
	"\aConsume\x12,.dogma.interop.v1.eventstream.ConsumeRequest\x1a-.dogma.interop.v1.eventstream.ConsumeResponse0\x01\x12o\n" +
	"\n" +
	"EventTypes\x12/.dogma.interop.v1.eventstream.EventTypesRequest\x1a0.dogma.interop.v1.eventstream.EventTypesResponseB1Z/github.com/dogmatiq/interopspec/eventstreamspecb\x06proto3"

var (
	file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescData []byte
)

func file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDescData
}

var file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_goTypes = []any{
	(*ConsumeRequest)(nil),          // 0: dogma.interop.v1.eventstream.ConsumeRequest
	(*ConsumeResponse)(nil),         // 1: dogma.interop.v1.eventstream.ConsumeResponse
	(*EventTypesRequest)(nil),       // 2: dogma.interop.v1.eventstream.EventTypesRequest
	(*EventTypesResponse)(nil),      // 3: dogma.interop.v1.eventstream.EventTypesResponse
	(*EventType)(nil),               // 4: dogma.interop.v1.eventstream.EventType
	(*UnrecognizedApplication)(nil), // 5: dogma.interop.v1.eventstream.UnrecognizedApplication
	(*UnrecognizedEventType)(nil),   // 6: dogma.interop.v1.eventstream.UnrecognizedEventType
	(*NoRecognizedMediaTypes)(nil),  // 7: dogma.interop.v1.eventstream.NoRecognizedMediaTypes
	(*UnsupportedStartPoint)(nil),   // 8: dogma.interop.v1.eventstream.UnsupportedStartPoint
	(*envelopespec.Envelope)(nil),   // 9: dogma.interop.v1.envelope.Envelope
}
var file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_depIdxs = []int32{
	4, // 0: dogma.interop.v1.eventstream.ConsumeRequest.event_types:type_name -> dogma.interop.v1.eventstream.EventType
	9, // 1: dogma.interop.v1.eventstream.ConsumeResponse.envelope:type_name -> dogma.interop.v1.envelope.Envelope
	4, // 2: dogma.interop.v1.eventstream.EventTypesResponse.event_types:type_name -> dogma.interop.v1.eventstream.EventType
	0, // 3: dogma.interop.v1.eventstream.StreamAPI.Consume:input_type -> dogma.interop.v1.eventstream.ConsumeRequest
	2, // 4: dogma.interop.v1.eventstream.StreamAPI.EventTypes:input_type -> dogma.interop.v1.eventstream.EventTypesRequest
	1, // 5: dogma.interop.v1.eventstream.StreamAPI.Consume:output_type -> dogma.interop.v1.eventstream.ConsumeResponse
	3, // 6: dogma.interop.v1.eventstream.StreamAPI.EventTypes:output_type -> dogma.interop.v1.eventstream.EventTypesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_init() }
func file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_init() {
	if File_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto != nil {
		return
	}
	file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes[0].OneofWrappers = []any{
		(*ConsumeRequest_Offset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto = out.File
	file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_goTypes = nil
	file_github_com_dogmatiq_interopspec_eventstreamspec_streamapi_proto_depIdxs = nil
}
