// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: github.com/dogmatiq/interopspec/wellknown/uuidpb/uuid.proto

package uuidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UUID is a size-optimized representation of an RFC 4122 UUID.
type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upper         uint64                 `protobuf:"varint,1,opt,name=upper,proto3" json:"upper,omitempty"`
	Lower         uint64                 `protobuf:"varint,2,opt,name=lower,proto3" json:"lower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetUpper() uint64 {
	if x != nil {
		return x.Upper
	}
	return 0
}

func (x *UUID) GetLower() uint64 {
	if x != nil {
		return x.Lower
	}
	return 0
}

var File_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDesc = "" +
	"\n" +
	";github.com/dogmatiq/interopspec/wellknown/uuidpb/uuid.proto\x12\x0edogma.protobuf\"2\n" +
	"\x04UUID\x12\x14\n" +
	"\x05upper\x18\x01 \x01(\x04R\x05upper\x12\x14\n" +
	"\x05lower\x18\x02 \x01(\x04R\x05lowerB2Z0github.com/dogmatiq/interopspec/wellknown/uuidpbb\x06proto3"

var (
	file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDescData []byte
)

func file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDescData
}

var file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_goTypes = []any{
	(*UUID)(nil), // 0: dogma.protobuf.UUID
}
var file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_init() }
func file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_init() {
	if File_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDesc), len(file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto = out.File
	file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_goTypes = nil
	file_github_com_dogmatiq_interopspec_wellknown_uuidpb_uuid_proto_depIdxs = nil
}
